use bytes::Bytes;
use http::{Extensions, HeaderMap};
use opentelemetry::KeyValue;
use tracing::info;

use crate::{
    app_state::AppState,
    config::policy::{OnUnavailable, POLICY_GRPC_EVALUATE_TIMEOUT},
    content_filter::request::{build_evaluate_request, vk_auth_present},
    error::{api::ApiError, internal::InternalError, invalid_req::InvalidRequestError},
};

/// HTTP/2 path generated by tonic from `evaluate.proto` `package` + `service` +
/// `rpc`.
const POLICY_EVALUATE_GRPC_PATH: &str = "/policy.v1.PolicyService/Evaluate";

/// Upper bound on bytes printed for `EvaluateRequest.body` (proto field 9).
const EVALUATE_REQUEST_BODY_LOG_MAX_BYTES: usize = 2048;

/// Default API `message` when policy returns empty `reason_message` and
/// `reason` while PII-cache forwarding requires non-empty `out_body`.
pub(crate) const PIICACHE_OUT_BODY_MISSING_DEFAULT_MSG: &str =
    "Policy did not return a rewritten request body for PII cache.";

/// After `PolicyService/Evaluate`, how the gateway should forward the HTTP
/// body toward the LLM.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ContentFilterForwardBody {
    /// Keep the inbound body collected before policy.
    UseOriginal,
    /// Replace the forward body with policy `out_body`.
    UseReplaced(Bytes),
}

/// Full return from `evaluate_for_vk_request`: forward-body decision and
/// optional model downgrade.
#[derive(Debug, Clone)]
pub struct ContentFilterResult {
    pub forward_body: ContentFilterForwardBody,
    /// Downgraded model name from policy (bare name, e.g. "gpt-4o-mini").
    /// `None` means no downgrade.
    pub change_model: Option<String>,
}

/// Inserted into request extensions when policy downgraded the model.
/// Downstream model-access checks (`enforce_direct_proxy_vk_model_policy`,
/// `enforce_vk_model_policy_for_source_endpoint`) skip validation when this
/// marker is present.
#[derive(Debug, Clone)]
pub struct PolicyModelOverride {
    pub original_model: String,
    pub downgraded_model: String,
}

#[must_use]
pub(crate) fn message_for_piicache_out_body_missing(reason_message: &str, reason: &str) -> String {
    let rm = reason_message.trim();
    if !rm.is_empty() {
        return rm.to_string();
    }
    let r = reason.trim();
    if !r.is_empty() {
        return r.to_string();
    }
    PIICACHE_OUT_BODY_MISSING_DEFAULT_MSG.to_string()
}

/// Maps policy `EvaluateResponse` to a forward-body decision when `allowed` is
/// already true. `piicache_forward_active` is design §3.2 (Redis `true` and
/// non-empty `EvaluateRequest.body` after attach).
pub(crate) fn forward_body_for_allowed_evaluate_response(
    piicache_forward_active: bool,
    out_body: &[u8],
    reason_message: &str,
    reason: &str,
) -> Result<ContentFilterForwardBody, InvalidRequestError> {
    if !piicache_forward_active {
        return Ok(ContentFilterForwardBody::UseOriginal);
    }
    if out_body.is_empty() {
        return Err(InvalidRequestError::PiicacheOutBodyMissing {
            message: message_for_piicache_out_body_missing(reason_message, reason),
        });
    }
    Ok(ContentFilterForwardBody::UseReplaced(
        Bytes::copy_from_slice(out_body),
    ))
}

/// Build the human-readable denial message from policy response fields.
/// Reused by dispatcher & mapper to construct the synthetic response body
/// for request-log when policy denies a request.
pub(crate) fn build_content_policy_denied_message(
    reason_message: &str,
    reason: &str,
    blocked_by: &str,
) -> String {
    let mut message = {
        let rm = reason_message.trim();
        if rm.is_empty() {
            let r = reason.trim();
            if r.is_empty() {
                "Content policy denied this request.".to_string()
            } else {
                r.to_string()
            }
        } else {
            rm.to_string()
        }
    };
    if !blocked_by.is_empty() {
        message.push_str(" (blocked_by: ");
        message.push_str(blocked_by);
        message.push(')');
    }
    message
}

/// Replace the `"model"` field in body JSON with `new_model`.
/// Returns `(new body, original model name)`; on invalid JSON or missing
/// `"model"`, returns input unchanged.
pub(crate) fn apply_model_downgrade(body: Bytes, new_model: &str) -> (Bytes, Option<String>) {
    let Ok(mut v) = serde_json::from_slice::<serde_json::Value>(&body) else {
        return (body, None);
    };
    let original = v.get("model").and_then(|m| m.as_str()).map(String::from);
    v["model"] = serde_json::Value::String(new_model.to_string());
    match serde_json::to_vec(&v) {
        Ok(out) => (Bytes::from(out), original),
        Err(_) => (body, None),
    }
}

/// Constructs the JSON bytes for the synthetic HTTP response body returned
/// to both the client and the request-log when policy denies a request.
/// Mirrors the `ContentPolicyDenied` arm in
/// `InvalidRequestError::into_response`.
pub(crate) fn policy_denied_error_response_json(message: &str) -> Vec<u8> {
    serde_json::to_vec(&crate::error::api::ErrorResponse {
        error: crate::error::api::ErrorDetails {
            message: message.to_string(),
            r#type: Some(crate::middleware::mapper::openai::INVALID_REQUEST_ERROR_TYPE.to_string()),
            param: None,
            code: Some("content_filter".to_string()),
        },
    })
    .unwrap_or_default()
}

fn unavailable_on_failure(
    app_state: &AppState,
    on_unavailable: OnUnavailable,
    message: String,
) -> Result<ContentFilterResult, ApiError> {
    match on_unavailable {
        OnUnavailable::Allow => {
            tracing::warn!(%message, "content filter unavailable; allowing per policy");
            app_state
                .0
                .metrics
                .vk
                .content_filter_unavailable
                .add(1, &[]);
            Ok(ContentFilterResult {
                forward_body: ContentFilterForwardBody::UseOriginal,
                change_model: None,
            })
        }
        OnUnavailable::Deny => Err(ApiError::Internal(InternalError::ContentFilterUnavailable(
            message,
        ))),
    }
}

/// Run content-filter policy for VK-authenticated requests when enabled.
#[allow(clippy::too_many_lines)]
pub async fn evaluate_for_vk_request(
    app_state: &AppState,
    headers: &HeaderMap,
    extensions: &Extensions,
    body: &Bytes,
) -> Result<ContentFilterResult, ApiError> {
    let cfg = &app_state.config().policy;
    if !cfg.enabled || !vk_auth_present(extensions) {
        return Ok(ContentFilterResult {
            forward_body: ContentFilterForwardBody::UseOriginal,
            change_model: None,
        });
    }
    let Some(client) = app_state.content_filter_client().await else {
        return unavailable_on_failure(
            app_state,
            cfg.on_unavailable,
            "content filter client not initialised".to_string(),
        );
    };
    let Some(ctx) = extensions.get::<std::sync::Arc<crate::types::extensions::RequestContext>>()
    else {
        return Ok(ContentFilterResult {
            forward_body: ContentFilterForwardBody::UseOriginal,
            change_model: None,
        });
    };
    let Some(auth) = ctx.auth_context.as_ref() else {
        return Ok(ContentFilterResult {
            forward_body: ContentFilterForwardBody::UseOriginal,
            change_model: None,
        });
    };
    let Some(mut grpc_req) = build_evaluate_request(extensions, headers, auth, body) else {
        return Ok(ContentFilterResult {
            forward_body: ContentFilterForwardBody::UseOriginal,
            change_model: None,
        });
    };
    let headers_len = grpc_req.headers.len();

    let workspace_id = grpc_req.workspace_id.clone();
    crate::content_filter::piicache::attach_request_body_from_piicache_redis(
        app_state.redis(),
        &workspace_id,
        body,
        &mut grpc_req,
        &app_state.0.metrics.vk,
    )
    .await;

    crate::content_filter::estimate::fill_evaluate_request_estimates(
        app_state,
        headers,
        extensions,
        body,
        &mut grpc_req,
    )
    .await;

    let piicache_forward_active = !grpc_req.body.is_empty();

    let policy_request_link = format!(
        "{}{}",
        cfg.grpc_endpoint.trim_end_matches('/'),
        POLICY_EVALUATE_GRPC_PATH
    );
    let body_len = grpc_req.body.len();
    let preview_end = body_len.min(EVALUATE_REQUEST_BODY_LOG_MAX_BYTES);
    let body_utf8_lossy_preview = String::from_utf8_lossy(&grpc_req.body[..preview_end]);
    let body_preview_suffix = if body_len > EVALUATE_REQUEST_BODY_LOG_MAX_BYTES {
        "...(truncated for log)"
    } else {
        ""
    };
    // Log header count only; avoid logging sensitive header values.
    info!(
        "content_filter: policy Evaluate request | policy_grpc_endpoint={} \
         policy_grpc_path={} policy_request_link={} workspace_id={} \
         request_id={} virtual_key_id={} model={} provider={} client_ip={} \
         locale={} department_id={} headers_len={} body_len={} \
         estimated_input_tokens={} estimated_input_usd={} body_utf8_lossy={}{}",
        cfg.grpc_endpoint,
        POLICY_EVALUATE_GRPC_PATH,
        policy_request_link,
        grpc_req.workspace_id,
        grpc_req.request_id,
        grpc_req.virtual_key_id,
        grpc_req.model,
        grpc_req.provider,
        grpc_req.client_ip,
        grpc_req.locale,
        grpc_req.department_id,
        headers_len,
        body_len,
        grpc_req.estimated_input_tokens,
        grpc_req.estimated_input_usd,
        body_utf8_lossy_preview,
        body_preview_suffix,
    );

    let mut inner = client.inner();
    let call = inner.evaluate(grpc_req);
    let result = tokio::time::timeout(POLICY_GRPC_EVALUATE_TIMEOUT, call).await;

    match result {
        Ok(Ok(resp)) => {
            let inner_resp = resp.into_inner();
            info!(
                "content_filter: policy Evaluate response allowed={} \
                 reason={} blocked_by={} route_hint={} snapshot_revision={} \
                 reason_message={} out_body_len={} out_body={} change_model={}",
                inner_resp.allowed,
                inner_resp.reason,
                inner_resp.blocked_by,
                inner_resp.route_hint,
                inner_resp.snapshot_revision,
                inner_resp.reason_message,
                inner_resp.out_body.len(),
                String::from_utf8_lossy(&inner_resp.out_body),
                inner_resp.change_model,
            );
            if inner_resp.allowed {
                let change_model = {
                    let cm = inner_resp.change_model.trim();
                    if cm.is_empty() {
                        None
                    } else {
                        Some(cm.to_string())
                    }
                };
                let plan = match forward_body_for_allowed_evaluate_response(
                    piicache_forward_active,
                    &inner_resp.out_body,
                    &inner_resp.reason_message,
                    &inner_resp.reason,
                ) {
                    Ok(p) => p,
                    Err(e) => {
                        app_state
                            .0
                            .metrics
                            .vk
                            .policy_piicache_request_body
                            .add(1, &[KeyValue::new("outcome", "out_body_missing_400")]);
                        return Err(ApiError::InvalidRequest(e));
                    }
                };
                match &plan {
                    ContentFilterForwardBody::UseOriginal => {}
                    ContentFilterForwardBody::UseReplaced(_) => {
                        app_state.0.metrics.vk.policy_piicache_request_body.add(
                            1,
                            &[KeyValue::new("outcome", "forward_replaced_with_out_body")],
                        );
                    }
                }
                app_state.0.metrics.vk.content_filter_allowed.add(1, &[]);
                return Ok(ContentFilterResult {
                    forward_body: plan,
                    change_model,
                });
            }
            app_state.0.metrics.vk.content_filter_denied.add(1, &[]);
            let message = build_content_policy_denied_message(
                &inner_resp.reason_message,
                &inner_resp.reason,
                &inner_resp.blocked_by,
            );
            Err(ApiError::InvalidRequest(
                InvalidRequestError::ContentPolicyDenied { message },
            ))
        }
        Ok(Err(status)) => {
            tracing::info!(
                grpc_code = ?status.code(),
                grpc_message = %status.message(),
                details = %status,
                "content_filter: policy Evaluate gRPC error response"
            );
            app_state
                .0
                .metrics
                .vk
                .content_filter_unavailable
                .add(1, &[]);
            unavailable_on_failure(app_state, cfg.on_unavailable, status.to_string())
        }
        Err(_elapsed) => {
            tracing::info!(
                timeout_secs = POLICY_GRPC_EVALUATE_TIMEOUT.as_secs_f64(),
                "content_filter: policy Evaluate timed out (no gRPC response \
                 body)"
            );
            app_state
                .0
                .metrics
                .vk
                .content_filter_unavailable
                .add(1, &[]);
            unavailable_on_failure(
                app_state,
                cfg.on_unavailable,
                "content filter evaluate timed out".to_string(),
            )
        }
    }
}

#[cfg(test)]
mod forward_body_tests {
    use super::{
        ContentFilterForwardBody, PIICACHE_OUT_BODY_MISSING_DEFAULT_MSG,
        forward_body_for_allowed_evaluate_response, message_for_piicache_out_body_missing,
    };
    use crate::error::invalid_req::InvalidRequestError;

    #[test]
    fn inactive_ignores_out_body() {
        assert_eq!(
            forward_body_for_allowed_evaluate_response(false, b"replaced", "", "",).unwrap(),
            ContentFilterForwardBody::UseOriginal,
        );
    }

    #[test]
    fn active_nonempty_out_body_replaced() {
        let got = forward_body_for_allowed_evaluate_response(true, b"replaced", "m", "r").unwrap();
        match got {
            ContentFilterForwardBody::UseReplaced(b) => {
                assert_eq!(&b[..], b"replaced");
            }
            ContentFilterForwardBody::UseOriginal => {
                panic!("expected replaced")
            }
        }
    }

    #[test]
    fn active_empty_out_body_err() {
        let err = forward_body_for_allowed_evaluate_response(true, b"", "  hi  ", "").unwrap_err();
        match err {
            InvalidRequestError::PiicacheOutBodyMissing { message } => {
                assert_eq!(message, "hi");
            }
            e => panic!("unexpected {e:?}"),
        }
    }

    #[test]
    fn message_fallback_chain() {
        assert_eq!(
            message_for_piicache_out_body_missing("", ""),
            PIICACHE_OUT_BODY_MISSING_DEFAULT_MSG,
        );
        assert_eq!(message_for_piicache_out_body_missing("", "r0"), "r0",);
        assert_eq!(message_for_piicache_out_body_missing("m0", "r0"), "m0",);
    }
}

#[cfg(test)]
mod model_downgrade_tests {
    use bytes::Bytes;

    use super::apply_model_downgrade;

    #[test]
    fn replaces_model_in_valid_json() {
        let body = Bytes::from(r#"{"model":"gpt-4o","messages":[]}"#);
        let (new_body, original) = apply_model_downgrade(body, "gpt-4o-mini");
        let v: serde_json::Value = serde_json::from_slice(&new_body).unwrap();
        assert_eq!(v["model"], "gpt-4o-mini");
        assert_eq!(original, Some("gpt-4o".to_string()));
    }

    #[test]
    fn no_model_field_returns_original_unchanged() {
        let body = Bytes::from(r#"{"messages":[]}"#);
        let (new_body, original) = apply_model_downgrade(body.clone(), "gpt-4o-mini");
        let v: serde_json::Value = serde_json::from_slice(&new_body).unwrap();
        assert_eq!(v["model"], "gpt-4o-mini");
        assert_eq!(original, None);
    }

    #[test]
    fn invalid_json_returns_body_unchanged() {
        let body = Bytes::from("not json");
        let (new_body, original) = apply_model_downgrade(body.clone(), "gpt-4o-mini");
        assert_eq!(new_body, body);
        assert_eq!(original, None);
    }
}
